/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Test_Jni */

#ifndef _Included_Test_Jni
#define _Included_Test_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test_Jni
 * Method:    CharJoin
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Test_1Jni_CharJoin
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Test_Jni
 * Method:    CharJoin2
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Test_1Jni_CharJoin2
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
